vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
    
    mappings:
       entity_image:
           uri_prefix: /uploads/trajet
           upload_destination: '%kernel.project_dir%/public/uploads/trajet'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
